# Generated by Django 4.1.1 on 2022-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_super_admin', models.BooleanField(default=False, help_text='Designates whether the user is owner/creator of organization', verbose_name='admin status')),
                ('is_admin', models.BooleanField(default=False, help_text='designates whether the user can log into admin site of the organization', verbose_name='admin status')),
                ('is_employee', models.BooleanField(verbose_name=models.BooleanField(default=False, verbose_name='employee status'))),
                ('is_pms_root', models.BooleanField(default=False, help_text='designates whether the pms user is super user', verbose_name='pms_root status')),
                ('is_active', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(null=True, verbose_name='info updated')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
