# Generated by Django 4.1.1 on 2022-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_pmsuser_options_pmsuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Invitation and email confirmation status'),
        ),
        migrations.AddField(
            model_name='pmsuser',
            name='email_confirmed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pmsuser',
            name='is_employee',
            field=models.BooleanField(default=False, null=True, verbose_name='employee status'),
        ),
    ]
