# Generated by Django 4.1.1 on 2022-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='is_on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 999.99'}}, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 999.99'}}, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 999.99'}}, max_digits=5, null=True),
        ),
    ]
