# Generated by Django 4.1.1 on 2022-09-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productinventory_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='upc',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
