# Generated by Django 4.1.1 on 2022-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productinventory_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='name',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='upc',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
