# Generated by Django 4.1.1 on 2022-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_productinventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='sku',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='upc',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
