# Generated by Django 4.1.1 on 2022-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productinventory_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='activated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
