# Generated by Django 4.1.1 on 2022-09-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_brand_stock_productinventory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='inventory.productinventory'),
        ),
    ]
