# Generated by Django 4.1.1 on 2022-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_productinventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
